### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by eirichmond** [wordpress-juanmaguitar/tt4-dh-alternatives-custom-blocks#1]
I noticed in the instructions it refers to setting up a plugin but it is infact a theme :)
https://github.com/wordpress-juanmaguitar/tt4-dh-alternatives-custom-blocks?tab=readme-ov-file#development

**Comment by juanmaguitar** [comment]
Thanks @eirichmond! 🙌
Closing this issue as https://github.com/wptrainingteam/tt4-dh-alternatives-custom-blocks/pull/2 has been merged
